#ifndef CLUSTER_COMMON_SH_HEADER_GUARD
#define CLUSTER_COMMON_SH_HEADER_GUARD

//#if BGFX_SHADER_LANGUAGE_SPIRV
//    #undef BGFX_SHADER_LANGUAGE_HLSL
//    #define BGFX_SHADER_LANGUAGE_HLSL 5
//#endif

#endif // COMMON_SH_HEADER_GUARD
